apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-app
    zone: dev
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: web-app